### ISSUE TITLE
Nice vagrant box, I don't want to abuse but... how can I change the language from german to english or spanish? 

### ISSUE THREAD

**Issue by pabloselin** [tommy-muehle/puppet-vagrant-boxes#1]

**Comment by pabloselin** [comment]
don't worry, I figured it out! Thanks!

**Comment by tommy-muehle** [comment]
Hi Pablo,

thanks for your feedback. I didn't thought about the VM language. But you can
easily search through the script files and change the "de_DE" setting to "en_US",
or whatever you prefer. The timezone is set to "Europe/Berlin", too, so pay
attention if you chnage the language values.

Next time I'll make it configurable.

Sincerly, Tommy

**Comment by ccolorado** [comment]
This file fixes it on reboot

```
$ cat /etc/environment 
LANG="en_US.UTF-8"
LC_COLLATE="C"
LC_TIME="en_US.UTF-8"
LC_ALL="C"
```

**Comment by joseche** [comment]
are you planning on defaulting to english ?
